### ISSUE TITLE
why H264 is NOT supported: Plugin 'openh264' not found?

### ISSUE THREAD

**Issue by kingkasuo** [Kurento/bugtracker#255]
0:00:39.339096345     1 0x7f3d40003630 WARN    KurentoWebRtcEndpointImpl WebRtcEndpointImpl.cpp:125:check_support_for_h264: H264 is NOT supported: Plugin 'openh264' not found

**Comment by kingkasuo** [comment]
I`m running in docker container ~

**Comment by jlongman** [comment]
It's not installed by default because the plugin that implements it downloads a proprietary binary blob from cisco.  

> `openh264-gst-plugins-bad-1.5` must be installed on the system
and
> `openh264` must be _correctly_ installed.

from: https://docs.google.com/document/d/1gbhJxZEIzSQR5yHwWXgQw_UxCjhJSc8_BEmYgChP8DI/

`sudo apt-get install openh264-gst-plugins-bad-1.5` will download both.  Then restart `kurento-media-server`.

**Comment by kingkasuo** [comment]
thanks~ I have used compiled version, problem solved.
