### ISSUE TITLE
What is the exact procedure to create a JS client from customer module?

### ISSUE THREAD

**Issue by neilyoung** [Kurento/bugtracker#284]
Hi,

I have now followed this tutorial several times to no avail http://doc-kurento.readthedocs.io/en/stable/user/writing_modules.html

- I'm able to create a custom module
- I'm able to create the ./js and ./kurento-client.js folders
- I'm able to produce something in both js folders ./dist using npm and grunt

I'm NOT able to create a combined kurento-client.js, which contains my interface class (as it can be seen in the JS samples).

In the JS client sample code there is always a kurento-client.js, which contains the code for the filters, e.g. FaceOverlayfilter. I just have one file (./js/dist/mymodule.js) and a kurento-client.js in ./kurento-client.js/dist, which does not contain my class. Do I have to stich them together manually?

**Comment by neilyoung** [comment]
Anybody?

**Comment by neilyoung** [comment]
It would have been very helpful, if someone somewhere would have mentioned, that there is an extra registration required...Worth two days of head scratching...

`kurentoClient.register('kurento-module-myfancymodule')
`

**Comment by KyleFoleyImajion** [comment]
@neilyoung since this project is open source and the Kurento team is very small, it would be helpful if you contributed to the project by creating pull request for all of these issues you are running into. The Kurento team also has commercial support, which not only helps you solve your issue faster, but it also helps support them. 

If you were to look at the VERY FIRST line of this [documentation code example](http://doc-kurento.readthedocs.io/en/stable/tutorials/js/module-chromafilter.html) towards the middle of the page, you would see where it clearly says `kurentoClient.register('kurento-module-chroma')`. Do some research before submitting a bug and begging for help.

**Comment by neilyoung** [comment]
Yes, unfortunately I was using the magic-mirror example, since this is what attracted me most. There is no extra registration, this lead me to the wrong way. Sure, my bad. But there is no speech about extra registration in all of your documentation around "How to make a custom module". Would be worth to add...

**Comment by neilyoung** [comment]
Other than that: It works great

**Comment by adrianimajion** [comment]
@neilyoung Kyle specifically cited the documentation containing the information you insist is missing.

It seems like you are new to the community so as a word of guidance, please **do not utilize open source projects' bug trackers as help forums.** The Kurento team has a full plate and strict guidelines for bug report submission and this makes effective work more challenging for everyone. You seem to be great at spotting areas that need improvement, so please consider the fact that this is an open source community effort by contributing work on those improvements yourself. 

Documentation is often the most neglected component of an open source project because primary contributors are hard at work on the code itself, so Kurento actually has some of the best out there, comparatively. **Updating documentation is a great way for new project members like you to begin contributing in a constructive way.**
