### ISSUE TITLE
Docker Versioning does not match source

### ISSUE THREAD

**Issue by jason-fox** [Kurento/bugtracker#337]
There has been one release of [Kurento Docker](https://github.com/Kurento/kurento-docker/releases)

This is referred to as **6.8.0**, however the `Dockerfile` is downloading **6.0** - a much older release

https://github.com/Kurento/kurento-docker/blob/master/docker/Dockerfile#L15

Please do the following:

1)  Amend to the line to  **6.8.0**  to overwrite the existing incorrect release
    -  and push to *6.8.0* to Docker Hub
    - Make a release *6.8.0* on Docker Hub
2)  Amend to the line to  **6.8.1** to create the missing release
    -  and push to *6.8.1* to Docker Hub
    - Make a release *6.8.1* on Docker Hub
3)  Amend to the line to  **6.9.0** to create the missing release
    -  and push to *6.9.0* to Docker Hub
    - Make a release *6.9.0* on Docker Hub

So that the releases align with the tags found in the [Media Server Repo](https://github.com/Kurento/kurento-media-server/)

**Comment by j1elo** [comment]
Hi, the `kurento-docker` repo doesn't really contain any Git tag because _all_ of the Dockerfiles used by all Kurento sub-projects are stored there. Having git tags wouldn't make any sense (*which Dockerfile does the tag refer to?*).

All Docker image releases are appropriately tagged in the home page of Docker images, this is, the corresponding project page inside Docker Hub. E.g. the Kurento Media Server Docker images are here: https://hub.docker.com/r/kurento/kurento-media-server/tags

It is true that the `kurento-docker` repo had a tag named "6.8.0" until yesterday (it has been deleted now). This was mistakenly created by a misconfigured automatic CI job some weeks ago, so it was an error having it here.

**Comment by j1elo** [comment]
As of 2019 the Docker images that get released are built upon Ubuntu Xenial, this is an LTS release so it should be supported officially until 2020. During that time the project needs to be fully ported to Ubuntu Bionic.

We are also seeing they way to add FIWARE tags to the current tags, so any given Docker image of Kurento Media Server is also tagged with the FIWARE version that corresponds to that release.

**Comment by jason-fox** [comment]
Interesting. So it looks like the  (awkwardly named) FIWARE clone - [here](https://hub.docker.com/r/fiware/stream-oriented-kurento/tags) - isn't properly following https://hub.docker.com/r/kurento/kurento-media-server at them moment.

**Comment by jason-fox** [comment]
stale
