### ISSUE TITLE
Kurento for multiple streams

### ISSUE THREAD

**Issue by pooja1pathak** [Kurento/bugtracker#403]
Hi Kurento-Team,

I have created kurento backend client to show multiple camera streams from different camera on single tab.

I have tested the same on android with firefox with version 67.0. It is working fine, showing multiple streams at the same time.

But when I try to do the same on my desktop/laptop(windows) with firefox version 69, It fails on playing second stream stating ICE candidate fails. In Kurento console log I get the error in adding candidate.

Please guide me how to resolve this issue.

Thanks in advance.

**Comment by j1elo** [comment]
Hi, this is due to a change in Firefox, that sends an empty candidate when the ICE candidate gathering is finished.

We have recently fixed it, but it's not yet released. The fix will be part of Kurento 6.12... meanwhile, you can either remove empty candidates (in your application server), or use [Kurento nightly](https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html) if that's acceptable.

Related:
* https://groups.google.com/d/topic/kurento/P_IEvYKyoJ0/discussion
* https://groups.google.com/d/msg/kurento/No3L5V75ayE/vxNBuyMBDAAJ
* https://groups.google.com/d/msg/kurento/No3L5V75ayE/MChVI-6qAAAJ
