### ISSUE TITLE
rtmp to rtp problem

### ISSUE THREAD

**Issue by amiznikov** [Kurento/bugtracker#404]
**KMS Version**:

6.11.0

**Ubuntu Version**

16.04

**Other libraries versions**:

GStreamer Core Library version 1.8.3

**Client libraries**

https://github.com/Kurento/kurento-tutorial-java/tree/master/kurento-rtp-receiver

**What steps will reproduce the problem?**

1. start it https://github.com/Kurento/kurento-tutorial-java/tree/master/kurento-rtp-receiver
2. gstreamer start with settings
PEER_A=audio_port PEER_V=video_port PEER_IP=ip_server \
SELF_PATH="rtmp://streamrtmp:port/?key" \
SELF_A=5006 SELF_ASSRC=445566 \
SELF_V=5004 SELF_VSSRC=112233 \
GST_DEBUG=4 \
bash -c 'gst-launch-1.0 -e \
  rtpbin name=r sdes="application/x-rtp-source-sdes,cname=(string)\"user\@example.com\"" \
  rtmpsrc location="$SELF_PATH live=1" ! decodebin name=d \
  d. ! queue ! audioconvert ! opusenc \
    ! rtpopuspay ! "application/x-rtp,payload=(int)96,clock-rate=(int)48000,ssrc=(uint)$SELF_ASSRC" \
    ! r.send_rtp_sink_0 \
  d. ! queue ! videoconvert ! x264enc tune=zerolatency \
    ! rtph264pay ! "application/x-rtp,payload=(int)103,clock-rate=(int)90000,ssrc=(uint)$SELF_VSSRC" \
    ! r.send_rtp_sink_1 \
  r.send_rtp_src_0 ! udpsink host=$PEER_IP port=$PEER_A bind-port=$SELF_A \
  r.send_rtcp_src_0 ! udpsink host=$PEER_IP port=$((PEER_A+1)) bind-port=$((SELF_A+1)) sync=false async=false \
  udpsrc port=$((SELF_A+1)) ! r.recv_rtcp_sink_0 \
  r.send_rtp_src_1 ! udpsink host=$PEER_IP port=$PEER_V bind-port=$SELF_V \
  r.send_rtcp_src_1 ! udpsink host=$PEER_IP port=$((PEER_V+1)) bind-port=$((SELF_V+1)) sync=false async=false \
  udpsrc port=$((SELF_V+1)) ! tee name=t \
    t. ! queue ! r.recv_rtcp_sink_1 \
    t. ! queue ! fakesink dump=true async=false'  

**What is the expected result?**

i may see rtp stream

**What happens instead?**

i've got some error

![name](https://user-images.githubusercontent.com/2655803/65876348-b486b180-e391-11e9-8edb-c51ec01cdfd6.jpg)

**Comment by j1elo** [comment]
Hi,

note this line:

```
ERROR: from element /GstPipeline:pipeline0/GstRTMPSrc:rtmpsrc0: Internal data flow error
```

The problem is in the `rtmpsrc` element you are using. The resulting audio is not valid, and the `audioconvert` element doesn't know what to do with it:

```
<audioconvert0> transform could not transform audio/x-raw, [...], channel-mask=(bitmask)0x03 in anything we support
```

I've googled a bit about `channel-mask`, it seems that it gets used when using interleaved stereo audio, and valid values should be 0x00, 0x01, 0x02, 0x04, etc. But 0x03 seems like invalid:
* http://gstreamer-devel.966125.n4.nabble.com/audioconvert-refuses-to-convert-mono-into-stereo-in-Gstreamer-1-09-td4662260.html
* https://gstreamer.freedesktop.org/documentation/audio/gstaudiochannels.html?gi-language=c#enumerations

You'll have to gain a better understanding of what is the source audio encoding in the RTMP server, and see how to provide valid audio to your GStreamer command. Please ask in GStreamer lists or in Kurento mailing list to see if someone can help you with the encodings.

In any case, this is not a bug in Kurento.

Also don't post screen captures, when you can just copy & paste the logs between ``` marks: https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code

**Comment by amiznikov** [comment]
Thanks for the detailed response!:)
