### ISSUE TITLE
Memory leaks when recording files with audio

### ISSUE THREAD

**Issue by shofel** [Kurento/bugtracker#408]
I wrote this a day after the experiment. That is why the data is not strictly accurate.

# Versions
- KMS version: 6.11
- Ubuntu version: 18.04
- Browser: Chrome 76
- Client library: kurento-utils-js@6.11.1

## Other libraries:

- Setup: KMS in docker; browsers run at the same host.

All info about memory and network IO is from `docker stats` output.

Set up:
- KMS writes each incoming stream to a file

# What I did

## File recorder profile = WEBM
What I done and observed:
1. Connect 15 senders to KMS. That is 15 tabs in Chrome browser, each sends one media stream.
1. After all the clients connected, memory consumption continues to grow. It roughly equals to the net IO of the container with Kurento.

## File recorder profile = WEBM_VIDEO_ONLY
1. Connect 15 senders to KMS.
1. Growth of memory consumption is far less noticeable (reduced by about 3 times)

## Also, Common for Both
1. Close all browser senders.
1. Memory consumption decreases by ~5MB. It doesn't matter, how much memory was in use - 5MB is freed.
2. Connect 15 senders again.
1. Memory usage starts to grow, almost without delay.

------

We also observed substantial difference in memory usage between `mpeg4` and `mpeg4 video only` profiles of writing files.

## Total
- Issue 1. KMS consumes 3 times more memory when writing files with audio, than writing audio only.
- Issue 2. Memory neither frees nor reused after senders disconnected.

**Comment by j1elo** [comment]
We're missing a proper announcement, but [Kurento 6.12](https://doc-kurento.readthedocs.io/en/6.12.0/project/relnotes/v6_12_0.html) was published with some bug fixes and maybe it improves the situation there, could you try it?

How are you measuring memory usage consumption? [Memory usage grows too high](https://doc-kurento.readthedocs.io/en/6.12.0/user/troubleshooting.html#memory-usage-grows-too-high) warns that using `ps` or `top` is a misleading method, and the way to find actual leaks is with Valgrind.

Please run KMS 6.12 with Valgrind to try and find any memory leaks we might have; the process has been hugely simplified, so it's just a matter of following the steps outlined in [Building from sources](https://doc-kurento.readthedocs.io/en/latest/dev/dev_guide.html#building-from-sources) **but** instead of

`bin/kms-build-run.sh`

you'll want to do

`bin/kms-build-run.sh --valgrind-memcheck`

Also please have a look at the information about our Docker image based on AddressSanitizer, in [Media Server Crashes](https://doc-kurento.readthedocs.io/en/6.12.0/user/troubleshooting.html#media-server-crashes). It might help finding issues if you run Kurento with this image.
