### ISSUE TITLE
Unable to access on different browsers or on incognito tab

### ISSUE THREAD

**Issue by devWaleed** [Kurento/bugtracker#416]
**KMS Version**:  6.12.0

**Ubuntu Version** 

Using Docker image on Windows 10

**What steps will reproduce the problem?**

i have setup KMS and OneToMany client. I am using Docker image. I am opening client in two tabs in Chrome. I click on presenter in one and i click on viewer in other. It works. But if the viewer tab is an incognito tab it doesnt work. Doesnt show stream

**What is the expected result?**

Should work in normal and incognito tab both and in other browsers as well

**What happens instead?**

Two tabs in normal mode will correctly, but if viewer tab is in incognito, viewer dont get video stream.

**Does it happen with one of the tutorials?**

Yes One To Many

**Please provide any additional information below**

I used docker container logs command to check logs and I see when viewer is connected to KMS, it gives error:

ERROR:  Adding remote candidate to ICE Agent failed, stream_id: 1

**Comment by j1elo** [comment]
Your test will work fine if you run Kurento local install, instead of Docker.

In incognito mode, or when it's the first time it runs the website (you can test by clearing all browser cookies), [Chrome hides the local IP behind an mDNS name](https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/), for privacy reasons.

But **Docker doesn't support mDNS**.



See:
* [mDNS ICE candidate fails: Name or service not known](https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html#mdns-ice-candidate-fails-name-or-service-not-known) ("*Caveat: mDNS does not work from within Docker*")
* [mDNS and Crossbar.io Fabric (Docker) #21](https://github.com/crossbario/crossbar-fabric-public/issues/21)

**Comment by devWaleed** [comment]
@j1elo I have two development environments, for Windows i read that only through Docker its possible. Other way is Amazon but its paid and I cant do it right now.

Second environment I have here is Ubuntu, should I go with that? Or is there a way with Windows ?

**Comment by j1elo** [comment]
Ubuntu is the preferred environment; this is a linux project and it is developed with Ubuntu 16.04 (but you can use either 16.04 or 18.04).

However if your preference is to stay on Windows, I think you can do that. You just need to avoid situations which make Chrome to hide the local IP with mDNS. These situations are (as far as I know):
1. Private tabs
2. First run ever (since cookie and cache cleanup)

So you should be able to develop your application fine on Windows, just avoiding those two cases.

**Comment by alexlapa** [comment]
@devWaleed, @j1elo,

You can disable mdns manually: chrome://flags/#enable-webrtc-hide-local-ips-with-mdns

**Comment by j1elo** [comment]
> @devWaleed, @j1elo,
> 
> You can disable mdns manually: `chrome://flags/#enable-webrtc-hide-local-ips-with-mdns`

Thanks, I forgot about that flag. Will add this to the [mDNS section](https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html#mdns-ice-candidate-fails-name-or-service-not-known) in the troubleshooting page.
