### ISSUE TITLE
Unable to get remote stream or track in case when a “remote stream” is attached by other peer “rtcPeer.peerConnection.addStream(remoteStream)

### ISSUE THREAD

**Issue by shubhddn01** [Kurento/bugtracker#440]
I'm unable to get any video stream from remote.

**Problem** : When a user initiate a call without any video device and in the middle of the call he/she plugs the webcam. 

Currently I'm adding a video track in peerConnection when a user plugs the webcam but unable to stream at other end. I have also generated the offer(which I have observed in one of the solution of webrtc)  but could not get any solution for this.

**Comment by delia-m** [comment]
If you want to receive remote stream without local stream, create offer with `offerToReceiveVideo` options and connect.
```
peerConnection.createOffer({
      offerToReceiveVideo: true,
      offerToReceiveAudio: true, // if you need
});
```

Current version doesn't support re-negotiation which means you need to create new peer connection to add track after connection made.

But seems they are working on it. See  #189

**Comment by j1elo** [comment]
The SipRtpEndpoint mentioned in #189 is only a renegotiation-capable endpoint for SIP phones. It won't add renegotiation capabilities to the Javascript part.

kurento-utils-js is only a thin layer of helper functions around the browser's RTCPeerConnection; however, as soon as you want to do something more advanced with it, we recommend that you drop kurento-utils altogether and write code directly against the RTCPeerConnection object in the browser.

I don't see any actual bug in the current code, so I'm closing this as not-a-bug (feel free to reopen if you think otherwise)
