### ISSUE TITLE
Allow Kurento Docker image executed as non-root user

### ISSUE THREAD

**Issue by jbabob** [Kurento/bugtracker#441]
## Prerequisites

* [x] I have read the SUPPORT document
  

* [x] I have checked the Troubleshooting Guide
  

* [x] I have tested with the latest version
  

## Issue description
I want to deploy a Kubernetes node with the official Kurento Docker image in it. It works locally in a Ubuntu VM, but when I try to deploy it through Azure devops with a non-root user, the container won't start. By looking at the logs, the last message the container generates before stopping is this: 'tee: /etc/hosts: Permission denied'. The issue seems to be coming from line 62 of the entry point file (https://github.com/Kurento/kurento-docker/blob/master/kurento-media-server/entrypoint.sh#L62).

## Context
My Kubernetes deployment yaml uses the parameter securityContext-runAsUser, therefore a non-root user is running the container and modifying /etc/hosts is not permitted.

## How to reproduce?
1. Create a Deployment yaml file with the following container:
          name: kurento-media-server
          image: kurento/kurento-media-server:latest
          imagePullPolicy: Always
2. Add security context to the spec:
        securityContext:
            runAsUser: 1234
3. Deploy it

This can also be reproduced by running the Docker image alone as a non-root user.

## Expected & current behavior
Kurento media server should start

## (Optional) Possible solution
Not sure what this line in entrypoint.sh is for. It should probably be removed because it will prevent running Kurento in any secure environment where running as root is not permitted. I tried creating a custom Docker image that runs Kurento and then changes the permissions for /etc/hosts, but Docker seems to ignore those changes.

## Environment info
I'm basically running the Magic Mirror tutorial (https://doc-kurento.readthedocs.io/en/stable/tutorials/java/tutorial-magicmirror.html) but in a Kubernetes node. My node has two containers, one running the Kurento media server and the other running the Magic Mirror server app.

### INFO: Kurento Media Server

* Kurento version:  6.13.0 (latest)
* Server OS: Ubuntu
* Installation method:
    
  - [ ] apt-get
    
  - [x] Docker
    
  - [ ] AWS
    
  - [ ] Built from sources
    

### INFO: Application Server
The application server in this case can be anything. I reproduced the issue with the Magic Mirror tutorial application server.

### Version details

```
kurento-media-server -v

lsb_release -a

dpkg -l | grep -Pi 'kurento|kms-|gst.*1.5|nice'
```
I cannot do this because the container won't start. This is the full output of the container before is stops:
+ BASE_RTP_FILE=/etc/kurento/modules/kurento/BaseRtpEndpoint.conf.ini
+ WEBRTC_FILE=/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ cat /etc/hosts
+ sed /::1/d
+ tee /etc/hosts
tee: /etc/hosts: Permission denied

**Comment by j1elo** [comment]
Hi, thanks for all the details you've shared. It allowed me to reproduce the issue easily in my local host, and from there I realized the very simple solution that this needed. The script was assuming user *root*, but I see that this isn't always the case. We'll just add `true` to prevent the script from failing when the running user doesn't have permissions to write on the file `/etc/hosts`:
https://github.com/Kurento/kurento-docker/blob/master/kurento-media-server/entrypoint.sh#L66

CI is running and in the next couple hours or so you should see an updated label ":latest" on https://hub.docker.com/r/kurento/kurento-media-server-dev/tags
please try it to confirm if the issue is fixed.

**Comment by jbabob** [comment]
Hi, thank you for the quick reply. I just tried it and it doesn't work. However I ran an local image as root and the entrypoint.sh in it doesn't have the fix in it. Should the fix already be in the latest version by now?

**Comment by jbabob** [comment]
Just noticed you linked the dev version and not the main one, I'll try with that instead

**Comment by jbabob** [comment]
Alright this seems to have fixed it, Kurento is running now

**Comment by jbabob** [comment]
I ran into the same when setting the environment variables for a STUN server. These are the log entries generated by the media server:
+ set_parameter /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini stunServerAddress stun.l.google.com
+ local FILE=/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
+ local PARAM=stunServerAddress
+ local VALUE=stun.l.google.com
+ local 'COMMENT=;'
+ local 'REGEX=^;?\s*stunServerAddress=.*'
+ grep --extended-regexp --quiet '^;?\s*stunServerAddress=.*' /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini     + sed --regexp-extended --in-place 's/^;?\s*stunServerAddress=.*/stunServerAddress=stun.l.google.com/' /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
sed: couldn't open temporary file /etc/kurento/modules/kurento/sedsx1lDH: Permission denied

**Comment by jbabob** [comment]
Should I raise a new issue for this?

**Comment by jbabob** [comment]
I was able to fix the issue by creating a Dockerfile that modifies the permissions for /etc/kurento. The Dockerfile looks like this:

`FROM kurento/kurento-media-server-dev:latest

RUN addgroup --gid 123 mygroup; \
    adduser --disabled-password --gecos "" --uid 123 --home /home/myproject --gid 123 my-user;

RUN chown -R my-user /etc/kurento`

This works for our needs, but one way to improve the official Docker image would be to add a user. This would allow pointing to this user rather than having to create one. This issue is likely to happen every time someone is trying to run Kurento media server as a non-root user with environment variables.

**Comment by jbabob** [comment]
@j1elo Is this also an issue that will be fixed in the future?

**Comment by j1elo** [comment]
I think this would be a good thing to fix. However, I'm not sure of _how_ to fix this in our Dockerfiles.

We could create a `kurento` user inside the containers, so everything is installed with permissions for this user, instead of `root`.

But then, we'll be in the same situation: `/etc/kurento` will belong to user `kurento` (say UID 1001), then if you [override the user](https://docs.docker.com/engine/reference/run/#user) with `docker run --user="2002"`, the newly ad-hoc user with UID=2002 will not be able to write any files on `/etc/kurento`. It will not be able to `chown -R 2002 /etc/kurento` either, right?

So it would be a matter of running KMS either with UID=0 (root), or UID=1001 (kurento). What is the actual difference, in reality, taking into account this is a container? (I'd understand for a locally-installed service)

I also worry that such change could break applications that know and expect that KMS runs as root (especially important for reading files in PlayerEndpoint, or writing files in RecorderEndpoint)

**Comment by j1elo** [comment]
We definitely don't have a good way of supporting `docker run --user=1234`, except for having all of the Kurento files under `/etc` with `chmod 666`, which would be overkill.

In commit Kurento/kurento-docker@9a750b9 I'm definitely making sure that users don't run with `--user`, as it is now explicitly not supported. Instead, the new environment variable `KMS_UID` can be user to have Kurento drop the root account and run as a different user, with the given UID for both its user and group id.
