### ISSUE TITLE
Send Chinese garbled using ShowDataChannel Demo

### ISSUE THREAD

**Issue by yangjunjie52** [Kurento/bugtracker#449]
Hello, I am Chinese, so I need to enter Chinese video to display, but it will be garbled when I enter Chinese. What should I do to display it normally?

**Comment by j1elo** [comment]
Maybe it is because the `kms-datachannelexample` module writes the text with the wrong font family?

The code is [here](https://github.com/Kurento/kms-datachannelexample/blob/292719beb191ba06121119af32f790e19e7dd97a/src/gst-plugins/kmsshowdata.c#L113), where it sets the [font-desc](https://gstreamer.freedesktop.org/documentation/pango/textoverlay.html?gi-language=c#textoverlay:font-desc) property of the GStreamer's *textoverlay* plugin.

Maybe you need to change there and use a font family that supports the Chinese subset of UTF-8 characters. I'm not sure if "Sans" is a valid font family, but `sans-serif` is definitely a valid name, so I would start by setting `font-desc` to `sans-serif, 26` and see if it helps.

If you make changes to kms-datachannelexample, you'll have to rebuild packages from it. Do so with this command:

```
cd kms-datachannelexample/
docker run --rm \
    --mount type=bind,src="$PWD",dst=/hostdir \
    kurento/kurento-buildpackage:xenial \
    --install-kurento dev \
    --allow-dirty
```

(use `xenial` if you want to build for Ubuntu 16.04, and use `bionic` for Ubuntu 18.04)

Then install the package that will be generated, and re-test

**Comment by yangjunjie52** [comment]
Excuse me, I set up docker on linux environment
 v18 ubunto image, according to the official website tutorial in this environment, install the kurento-media-server and datachannelexample modules through the ‘install’ command. I want to ask, how do I cd datachannelexample, because I did n’t find its path in the environment? Or do I git datachannelexample?
Trouble you

**Comment by j1elo** [comment]
@yangjunjie52 this issue was not directly related to Kurento, but more with the fonts that are available in the system. I was able to solve it by installing some system fonts that contained UTF character set for Chinese. 

As I mention in Kurento/kms-datachannelexample/@/8b7dbdd, you need to install any system font that contains Chinese characters, such as `fonts-droid-fallback`, `fonts-wqy-microhei`, `fonts-noto`, `fonts-noto-cjk`. Those are just some examples.

I've added `fonts-droid-fallback` as a *recommended* (but not *mandatory*) dependency of `kms-datachannelexample`, for the next release.
