### ISSUE TITLE
Feature request for RecorderEndpoint and Kurento Repository

### ISSUE THREAD

**Issue by hdlopesrocha** [Kurento/bugtracker#49]
Hi! First of all thanks for your support, Kurento team has been awesome until now.

Some days ago I reported that videos recorded to Kurento Repository were creating non seekable videos. Mainly because the headers were being written in the beginning of the file and, on recording stop those headers would need to change.

I suggested adding an option to store the video only when finished recording, but I don't know if the following suggestion would be better.

If the recorder already knows the duration when starts recording, is it needed to update the header when it ends?

By the way I am very happy with your support, how can I donate you? You really deserve it.

**Comment by igracia** [comment]
@jcaden I seem to recall you were commenting with @hdlopesrocha in the list? What's your opinions on this? It's surely not in our roadmap, but maybe something to take into account?

@hdlopesrocha Thanks for your comments! We try to keep up with all requests as best as we can :-) There's no way right now to articulate donations, though you can send us a box of beers anytime!

**Comment by jcaden** [comment]
Hi,

We have implemented this already for MP4 format, when the destination uri is not seekable (not file), the video is buffered in a temporary file until stop is called. This has not been implemented for webm because webm files are recorder properly, except for the issue that they are not seekable. As any error on the kms or not calling to stop will end up with no video at all, we prefer to just store the video even if it is not seekable. You can create a seekable file easily from your application layer running `ffmpeg` like this:

    ffmpeg -i <input>.webm -c copy <output>.webm

Hope it can help you.
