### ISSUE TITLE
HTTP Streaming

### ISSUE THREAD

**Issue by repomaa** [Kurento/bugtracker#499]
I'm trying to use kurento to setup a service that merges video streams from multiple webrtc clients into an http stream. I noticed, that HttpGetClient has been removed from the codebase so I wondered: What is the current way to do this?

**Comment by j1elo** [comment]
I was curious about this because of not knowing about any HttpGet module in Kurento... it seems that HTTP GET feature was deemed deprecated during Kurento 5.x and removed since 6.0: https://github.com/Kurento/kms-elements/commit/98e37c727191cb026441b4159eb667389e883780

I would assume this feature was pretty much out of scope, or the team was unable to maintain all the features that were initially planned, so decided to cut the least used ones.

Still the idea behind the modular architecture of Kurento is that users should be able to write their own plugins and Endpoints. You can do so, the code is even there in the linked commit so you'd have a starting point (although it's been 4 years since its removal so it's probably not going to work as-is).

Otherwise you can still do the merge inside Kurento (with Composite) then output it with RtpEndpoint to some HTTP provider, or just use Kurento as a WebRTC/RTP gateway, and redirect all incoming WebRTC media through RTP to a service that does the mixing and publishing.

Closing this as it's not really a bug in Kurento.
