### ISSUE TITLE
Kurento tutorial having issue in Ubuntu server 

### ISSUE THREAD

**Issue by nishad1092** [Kurento/bugtracker#547]
I understand many people have opened similar issue, but still after reading I haven't got clarification.

**Environment**:
Ubuntu 18.04 server in Azure VM, 
Opened ports - 8888 and 8443.
After hosting the KMS in my Azure server, I'm accessing it through the Google chrome browser from my laptop(outside server)

**Version Installed:**

1.Installed from here https://doc-kurento.readthedocs.io/en/6.13.0/user/installation.html (except didn't configure TURN and STUN server, as I still don't understand the use of it)

2.Also followed this to support HTTPS (Trying NodeJS tutorial):  
https://doc-kurento.readthedocs.io/en/6.10.0/features/security.html#id1

**Tutorial tried:** 
Tried, HelloWorld and One2OneCall - NodeJs

**Execution**:

Executed in both npm start and npm start -- --ws_uri=ws://40.xx.xx.xx.xx:8443/kurento,

a. During npm start - I can see remote session window with loading,and doesn't stream, and in logs I can see: 

    Connection bAvBYDxksfV5zZQtwXrArSmI43Jf_XhP received message  {
      id: 'onIceCandidate',
    }
    Sending candidate

b. During npm start -- --ws_uri=ws://40.117.132.182:8888/kurento:

    Still not streaming, and I see in logs:
    Connection KFa-s8TGGc0_XwnwWf1rGDJU2xr-B_TD received message  {
        sdpMLineIndex: 1
      }
    }
    Queueing candidate
    reconnect to server 2 200 undefined
    reconnect to server 3 300 undefined

""""""""""""""""""""""""""""""""

What am I missing here, Why the stream isn't working. Please support me here.

**Comment by j1elo** [comment]
Hi, I normally reopen the issues that didn't follow the template but took the effort to do an explanation of the problem and provide useful information.

I'm acknowledging to have seen your issue, but I won't reopen it because it is not a bug in Kurento, but a misconception or misconfiguration from the user. Docs try to guide users through all the knowledge required to work with WebRTC (which is quite some), but it is still a low level tool and basic understanding must be applied to use it (otherwise I recommend to go for OpenVidu, which reduces a lot the knowledge surface required to operate)
