### ISSUE TITLE
Non-resolvable parent POM in tutorial project

### ISSUE THREAD

**Issue by andrew-koster-** [Kurento/bugtracker#8]
There appears to be a problem with the structure of the Maven projects, and I don't know these projects well enough to fix this structural problem.

I'm following the instructions in https://www.kurento.org/docs/current/tutorials/java/tutorial-3-one2many.html with the goal of setting up a basic media server.

I've created a new Ubuntu 14.04 machine for this purpose and cloned the sources just before the build, so everything is up to date.

```
root@chat-server-rtc:~/kurento-tutorial-java/kurento-one2many-call# mvn compile
exec:java
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.kurento.tutorial:kurento-one2many-call:6.1.1-SNAPSHOT
(/root/kurento-tutorial-java/kurento-one2many-call/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.kurento.tutorial:kurento-tutorial:
6.1.1-SNAPSHOT: Could not find artifact org.kurento:kurento-parent-pom:pom:6.1.1
-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ org.kurento.tuto
rial:kurento-tutorial:6.1.1-SNAPSHOT, /root/kurento-tutorial-java/pom.xml, line
5, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException
```

I opened the POM files in question and everything looks fine to me, but I'm far from an expert at Maven or at Kurento. This IS a tutorial project, it seems to me that it should Just Work for someone who isn't familiar with this software. Isn't that the point?

**Comment by igracia** [comment]
There is no problem with the structure of the project. You had just checked out the development version of the tutorials, which depends on a SNAPSHOT artifact. Since dev artifacts are not published in maven central, you need to checkout a release version of the projects, or add our development repo. Please read more in [this](https://stackoverflow.com/questions/32729319/error-trying-to-compile-kurento-java-tutorial-maven-dependency-resolution/32733585#32733585) stackoverflow answer.

We've updated the documentation to check out a release version, so this doesn't happen to new users.
